"""Reference vectors for the DeepSeek-V4 pieces implemented in dsv4.rs.

TRANSCRIBED from inference/kernel.py and inference/model.py, not re-derived from the
Rust — a re-derivation reproduces whatever misreading the Rust already contains. Where
the reference casts to a hardware float type, torch's own cast is used rather than a
hand-rolled rounding table, so the rounding is defined by the format and not by me.

Emits Rust literals for a #[test] in dsv4.rs.
"""
import math
import torch

torch.manual_seed(0)

# kernel.py:36  fast_round_scale(amax, fp8_max_inv) = fast_pow2(fast_log2_ceil(amax*inv))
# kernel.py:22  fast_log2_ceil: exponent - 127 + (mantissa != 0)
def fast_round_scale(amax: float, fmt_max_inv: float) -> float:
    t = torch.tensor([amax * fmt_max_inv], dtype=torch.float32)
    bits = t.view(torch.int32).item() & 0xFFFFFFFF
    exp = ((bits >> 23) & 0xFF) - 127
    man = bits & 0x7FFFFF
    return float(2.0 ** (exp + (1 if man else 0)))


# kernel.py:41 act_quant_kernel, inplace + round_scale branch (scale_fmt="ue8m0").
# amax floored at 1e-4; value clamped to +-448 then cast to FP8 and scaled back.
def act_quant_sim(x, block=64):
    out = x.clone()
    for i in range(0, x.numel(), block):
        blk = x[i:i + block]
        amax = max(blk.abs().max().item(), 1e-4)
        s = fast_round_scale(amax, 1.0 / 448.0)
        q = torch.clamp(blk / s, -448.0, 448.0).to(torch.float8_e4m3fn).float()
        out[i:i + block] = q * s
    return out


# kernel.py:129 fp4_quant_kernel, inplace branch. amax floored at 6*2^-126, scale from
# fast_round_scale(amax, 1/6), value clamped to +-6 then cast to FP4 (E2M1) and scaled.
# torch has no scalar e2m1 cast, so the level set IS the format: {0,.5,1,1.5,2,3,4,6},
# round-to-nearest-even on the mantissa bit.
_E2M1 = [0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0]
_EVEN = [True, False, True, False, True, False, True, False]


def _e2m1(v: float) -> float:
    a = abs(v)
    if a >= 6.0:
        return math.copysign(6.0, v)
    best = 0
    for k in range(1, 8):
        dk, db = abs(a - _E2M1[k]), abs(a - _E2M1[best])
        if dk < db or (dk == db and _EVEN[k] and not _EVEN[best]):
            best = k
    return math.copysign(_E2M1[best], v)


def fp4_act_quant_sim(x, block=32):
    out = x.clone()
    for i in range(0, x.numel(), block):
        blk = x[i:i + block]
        amax = max(blk.abs().max().item(), 6.0 * 2.0 ** -126)
        s = fast_round_scale(amax, 1.0 / 6.0)
        out[i:i + block] = torch.tensor(
            [_e2m1(min(max(v / s, -6.0), 6.0)) * s for v in blk.tolist()]
        )
    return out


# model.py:253 rotate_activation -> hadamard_transform(x, scale=size(-1)**-0.5).
# Sylvester / natural order, which is what fast_hadamard_transform implements.
def rotate_activation(x):
    n = x.numel()
    y = x.clone()
    h = 1
    while h < n:
        for i in range(0, n, h * 2):
            for j in range(i, i + h):
                a, b = y[j].item(), y[j + h].item()
                y[j], y[j + h] = a + b, a - b
        h *= 2
    return y * (n ** -0.5)


# model.py:206 precompute_freqs_cis. original_seq_len == 0 disables YaRN entirely.
def freqs(dim, seqlen, original_seq_len, base, factor, beta_fast, beta_slow):
    f = 1.0 / (base ** (torch.arange(0, dim, 2, dtype=torch.float32) / dim))
    if original_seq_len > 0:
        def corr(rot):
            return dim * math.log(original_seq_len / (rot * 2 * math.pi)) / (2 * math.log(base))
        low = max(math.floor(corr(beta_fast)), 0)
        high = min(math.ceil(corr(beta_slow)), dim - 1)
        if low == high:
            high += 0.001
        ramp = torch.clamp((torch.arange(dim // 2, dtype=torch.float32) - low) / (high - low), 0, 1)
        smooth = 1 - ramp
        f = f / factor * (1 - smooth) + f * smooth
    t = torch.arange(seqlen, dtype=torch.float32)
    ang = torch.outer(t, f)
    return torch.cos(ang), torch.sin(ang)


# model.py:408 Indexer.forward scoring:
#   score = einsum("bshd,btd->bsht", q, kv); (relu(score) * weights[...,None]).sum(dim=2)
def index_score(q, kv, w):
    s = torch.einsum("hd,td->ht", q, kv)
    return (torch.relu(s) * w[:, None]).sum(dim=0)


def fmt(v):
    return ", ".join(f"{x:.8}f32" for x in v)


print("// generated by scratchpad/ref_vectors.py — transcribed from inference/*.py")

x = (torch.arange(64, dtype=torch.float32) * 0.37).sin() * 3.0
print(f"const ACT_IN: [f32; 64] = [{fmt(x.tolist())}];")
print(f"const ACT_OUT: [f32; 64] = [{fmt(act_quant_sim(x, 64).tolist())}];")

y = (torch.arange(32, dtype=torch.float32) * 0.21).cos() * 5.0
print(f"const FP4_IN: [f32; 32] = [{fmt(y.tolist())}];")
print(f"const FP4_OUT: [f32; 32] = [{fmt(fp4_act_quant_sim(y, 32).tolist())}];")

h = (torch.arange(16, dtype=torch.float32) * 0.71).sin() * 2.0
print(f"const HAD_IN: [f32; 16] = [{fmt(h.tolist())}];")
print(f"const HAD_OUT: [f32; 16] = [{fmt(rotate_activation(h).tolist())}];")

# rope: compress layer (theta 160000, YaRN on) and non-compress (theta 10000, YaRN off)
c1, s1 = freqs(64, 8, 65536, 160000.0, 16.0, 32.0, 1.0)
print(f"const ROPE_C_COS: [f32; 32] = [{fmt(c1[7].tolist())}];")
c2, s2 = freqs(64, 8, 0, 10000.0, 16.0, 32.0, 1.0)
print(f"const ROPE_N_COS: [f32; 32] = [{fmt(c2[7].tolist())}];")

torch.manual_seed(7)
q = torch.randn(4, 8)
kv = torch.randn(5, 8)
w = torch.randn(4)
print(f"const IDX_Q: [f32; 32] = [{fmt(q.flatten().tolist())}];")
print(f"const IDX_KV: [f32; 40] = [{fmt(kv.flatten().tolist())}];")
print(f"const IDX_W: [f32; 4] = [{fmt(w.tolist())}];")
print(f"const IDX_SCORE: [f32; 5] = [{fmt(index_score(q, kv, w).tolist())}];")


# ---------------------------------------------------------------------------
# model.py:285 Compressor. Transcribed for the OVERLAP case (compress_ratio == 4),
# which is the intricate one: wkv/wgate emit `2*d`, the windows overlap, the softmax
# is per-DIMENSION over `2*ratio` entries, and prefill leaves a remainder in the carry
# state that the first decode steps then consume.
#
# The wkv/wgate matmuls are deliberately NOT included — they are ordinary matmuls
# covered elsewhere. Feeding their OUTPUTS isolates the pooling and the state carry,
# which is where this is hard to get right.
class RefCompressor:
    def __init__(self, ratio, d, ape):
        self.ratio, self.d, self.ape = ratio, d, ape
        self.overlap = ratio == 4
        coff = 1 + self.overlap
        slots = coff * ratio
        self.kv_state = torch.zeros(slots, coff * d)
        self.score_state = torch.full((slots, coff * d), float("-inf"))

    def overlap_transform(self, t, value):
        # t: [s, r, 2d] -> [s, 2r, d]
        s, r, d = t.size(0), self.ratio, self.d
        out = t.new_full((s, 2 * r, d), value)
        out[:, r:] = t[:, :, d:]
        out[1:, :r] = t[:-1, :, :d]
        return out

    def prefill(self, kv, score):
        seqlen, r, d = kv.size(0), self.ratio, self.d
        should = seqlen >= r
        remainder = seqlen % r
        cutoff = seqlen - remainder
        offset = r if self.overlap else 0
        if self.overlap and cutoff >= r:
            self.kv_state[:r] = kv[cutoff - r:cutoff]
            self.score_state[:r] = score[cutoff - r:cutoff] + self.ape
        if remainder > 0:
            self.kv_state[offset:offset + remainder] = kv[cutoff:]
            self.score_state[offset:offset + remainder] = score[cutoff:] + self.ape[:remainder]
            kv, score = kv[:cutoff], score[:cutoff]
        if not should:
            return None
        kv = kv.unflatten(0, (-1, r))
        score = score.unflatten(0, (-1, r)) + self.ape
        if self.overlap:
            kv = self.overlap_transform(kv, 0.0)
            score = self.overlap_transform(score, float("-inf"))
        return (kv * score.softmax(dim=1)).sum(dim=1)

    def decode(self, kv, score, start_pos):
        r, d = self.ratio, self.d
        should = (start_pos + 1) % r == 0
        score = score + self.ape[start_pos % r]
        if self.overlap:
            self.kv_state[r + start_pos % r] = kv
            self.score_state[r + start_pos % r] = score
            if not should:
                return None
            ks = torch.cat([self.kv_state[:r, :d], self.kv_state[r:, d:]], dim=0)
            ss = torch.cat([self.score_state[:r, :d], self.score_state[r:, d:]], dim=0)
            out = (ks * ss.softmax(dim=0)).sum(dim=0)
            self.kv_state[:r] = self.kv_state[r:]
            self.score_state[:r] = self.score_state[r:]
            return out
        self.kv_state[start_pos % r] = kv
        self.score_state[start_pos % r] = score
        if not should:
            return None
        return (self.kv_state * self.score_state.softmax(dim=0)).sum(dim=0)


torch.manual_seed(11)
R, D, S = 4, 8, 10          # 10 tokens => 2 full blocks + a remainder of 2
ape = torch.randn(R, 2 * D)
kvp = torch.randn(S, 2 * D)
scp = torch.randn(S, 2 * D)
c = RefCompressor(R, D, ape)
pre = c.prefill(kvp, scp)
print(f"const CMP_APE: [f32; {R * 2 * D}] = [{fmt(ape.flatten().tolist())}];")
print(f"const CMP_KV: [f32; {S * 2 * D}] = [{fmt(kvp.flatten().tolist())}];")
print(f"const CMP_SC: [f32; {S * 2 * D}] = [{fmt(scp.flatten().tolist())}];")
print(f"const CMP_PREFILL: [f32; {pre.numel()}] = [{fmt(pre.flatten().tolist())}];")

# then 8 decode steps from start_pos = S, collecting whatever they emit
dk = torch.randn(8, 2 * D)
ds = torch.randn(8, 2 * D)
emitted, at = [], []
for i in range(8):
    o = c.decode(dk[i], ds[i], S + i)
    if o is not None:
        emitted.append(o)
        at.append(i)
print(f"const CMP_DEC_KV: [f32; {8 * 2 * D}] = [{fmt(dk.flatten().tolist())}];")
print(f"const CMP_DEC_SC: [f32; {8 * 2 * D}] = [{fmt(ds.flatten().tolist())}];")
print(f"const CMP_DEC_AT: [usize; {len(at)}] = [{', '.join(str(i) for i in at)}];")
flat = torch.stack(emitted).flatten() if emitted else torch.zeros(0)
print(f"const CMP_DECODE: [f32; {flat.numel()}] = [{fmt(flat.tolist())}];")
