"""Reference vectors for the DeepSeek-V4 pieces implemented in dsv4.rs.

TRANSCRIBED from inference/kernel.py and inference/model.py, not re-derived from the
Rust — a re-derivation reproduces whatever misreading the Rust already contains. Where
the reference casts to a hardware float type, torch's own cast is used rather than a
hand-rolled rounding table, so the rounding is defined by the format and not by me.

Emits Rust literals for a #[test] in dsv4.rs.
"""
import math
import torch

torch.manual_seed(0)

# kernel.py:36  fast_round_scale(amax, fp8_max_inv) = fast_pow2(fast_log2_ceil(amax*inv))
# kernel.py:22  fast_log2_ceil: exponent - 127 + (mantissa != 0)
def fast_round_scale(amax: float, fmt_max_inv: float) -> float:
    t = torch.tensor([amax * fmt_max_inv], dtype=torch.float32)
    bits = t.view(torch.int32).item() & 0xFFFFFFFF
    exp = ((bits >> 23) & 0xFF) - 127
    man = bits & 0x7FFFFF
    return float(2.0 ** (exp + (1 if man else 0)))


# kernel.py:41 act_quant_kernel, inplace + round_scale branch (scale_fmt="ue8m0").
# amax floored at 1e-4; value clamped to +-448 then cast to FP8 and scaled back.
def act_quant_sim(x, block=64):
    out = x.clone()
    for i in range(0, x.numel(), block):
        blk = x[i:i + block]
        amax = max(blk.abs().max().item(), 1e-4)
        s = fast_round_scale(amax, 1.0 / 448.0)
        q = torch.clamp(blk / s, -448.0, 448.0).to(torch.float8_e4m3fn).float()
        out[i:i + block] = q * s
    return out


# kernel.py:129 fp4_quant_kernel, inplace branch. amax floored at 6*2^-126, scale from
# fast_round_scale(amax, 1/6), value clamped to +-6 then cast to FP4 (E2M1) and scaled.
# torch has no scalar e2m1 cast, so the level set IS the format: {0,.5,1,1.5,2,3,4,6},
# round-to-nearest-even on the mantissa bit.
_E2M1 = [0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0]
_EVEN = [True, False, True, False, True, False, True, False]


def _e2m1(v: float) -> float:
    a = abs(v)
    if a >= 6.0:
        return math.copysign(6.0, v)
    best = 0
    for k in range(1, 8):
        dk, db = abs(a - _E2M1[k]), abs(a - _E2M1[best])
        if dk < db or (dk == db and _EVEN[k] and not _EVEN[best]):
            best = k
    return math.copysign(_E2M1[best], v)


def fp4_act_quant_sim(x, block=32):
    out = x.clone()
    for i in range(0, x.numel(), block):
        blk = x[i:i + block]
        amax = max(blk.abs().max().item(), 6.0 * 2.0 ** -126)
        s = fast_round_scale(amax, 1.0 / 6.0)
        out[i:i + block] = torch.tensor(
            [_e2m1(min(max(v / s, -6.0), 6.0)) * s for v in blk.tolist()]
        )
    return out


# model.py:253 rotate_activation -> hadamard_transform(x, scale=size(-1)**-0.5).
# Sylvester / natural order, which is what fast_hadamard_transform implements.
def rotate_activation(x):
    n = x.numel()
    y = x.clone()
    h = 1
    while h < n:
        for i in range(0, n, h * 2):
            for j in range(i, i + h):
                a, b = y[j].item(), y[j + h].item()
                y[j], y[j + h] = a + b, a - b
        h *= 2
    return y * (n ** -0.5)


# model.py:206 precompute_freqs_cis. original_seq_len == 0 disables YaRN entirely.
def freqs(dim, seqlen, original_seq_len, base, factor, beta_fast, beta_slow):
    f = 1.0 / (base ** (torch.arange(0, dim, 2, dtype=torch.float32) / dim))
    if original_seq_len > 0:
        def corr(rot):
            return dim * math.log(original_seq_len / (rot * 2 * math.pi)) / (2 * math.log(base))
        low = max(math.floor(corr(beta_fast)), 0)
        high = min(math.ceil(corr(beta_slow)), dim - 1)
        if low == high:
            high += 0.001
        ramp = torch.clamp((torch.arange(dim // 2, dtype=torch.float32) - low) / (high - low), 0, 1)
        smooth = 1 - ramp
        f = f / factor * (1 - smooth) + f * smooth
    t = torch.arange(seqlen, dtype=torch.float32)
    ang = torch.outer(t, f)
    return torch.cos(ang), torch.sin(ang)


# model.py:408 Indexer.forward scoring:
#   score = einsum("bshd,btd->bsht", q, kv); (relu(score) * weights[...,None]).sum(dim=2)
def index_score(q, kv, w):
    s = torch.einsum("hd,td->ht", q, kv)
    return (torch.relu(s) * w[:, None]).sum(dim=0)


def fmt(v):
    return ", ".join(f"{x:.8}f32" for x in v)


print("// generated by scratchpad/ref_vectors.py — transcribed from inference/*.py")

x = (torch.arange(64, dtype=torch.float32) * 0.37).sin() * 3.0
print(f"const ACT_IN: [f32; 64] = [{fmt(x.tolist())}];")
print(f"const ACT_OUT: [f32; 64] = [{fmt(act_quant_sim(x, 64).tolist())}];")

y = (torch.arange(32, dtype=torch.float32) * 0.21).cos() * 5.0
print(f"const FP4_IN: [f32; 32] = [{fmt(y.tolist())}];")
print(f"const FP4_OUT: [f32; 32] = [{fmt(fp4_act_quant_sim(y, 32).tolist())}];")

h = (torch.arange(16, dtype=torch.float32) * 0.71).sin() * 2.0
print(f"const HAD_IN: [f32; 16] = [{fmt(h.tolist())}];")
print(f"const HAD_OUT: [f32; 16] = [{fmt(rotate_activation(h).tolist())}];")

# rope: compress layer (theta 160000, YaRN on) and non-compress (theta 10000, YaRN off)
c1, s1 = freqs(64, 8, 65536, 160000.0, 16.0, 32.0, 1.0)
print(f"const ROPE_C_COS: [f32; 32] = [{fmt(c1[7].tolist())}];")
c2, s2 = freqs(64, 8, 0, 10000.0, 16.0, 32.0, 1.0)
print(f"const ROPE_N_COS: [f32; 32] = [{fmt(c2[7].tolist())}];")

torch.manual_seed(7)
q = torch.randn(4, 8)
kv = torch.randn(5, 8)
w = torch.randn(4)
print(f"const IDX_Q: [f32; 32] = [{fmt(q.flatten().tolist())}];")
print(f"const IDX_KV: [f32; 40] = [{fmt(kv.flatten().tolist())}];")
print(f"const IDX_W: [f32; 4] = [{fmt(w.tolist())}];")
print(f"const IDX_SCORE: [f32; 5] = [{fmt(index_score(q, kv, w).tolist())}];")
