#!/usr/bin/env python3
"""Freeze the reference Kimi-K3 pre-tokenizer split into a Rust test fixture.

The Rust `k3_pretokenize` has to agree with K3's own `pat_str` (from
`tokenization_kimi.py`) on every input, or colibrì produces different token ids than the
model was trained on — silently, since every id is still in-vocabulary.

Rather than re-implement the pattern a second time inside the test (which would only
re-encode whatever I understood it to mean), this evaluates the ACTUAL pattern with the
`regex` module over a corpus and emits the results as a Rust fixture. The test then needs
no Python.

Usage:
    python3 scripts/gen_k3_pretok_cases.py > crates/colibri-tokenizer/tests/k3_pretok.rs
"""
import sys

try:
    import regex
except ImportError:
    raise SystemExit("needs the `regex` module: pip install regex")

# Verbatim from tokenization_kimi.py.
K3_PAT = "|".join([
    r"[\p{Han}]+",
    r"[^\r\n\p{L}\p{N}]?[[\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}]&&[^\p{Han}]]*"
    r"[[\p{Ll}\p{Lm}\p{Lo}\p{M}]&&[^\p{Han}]]+(?i:'s|'t|'re|'ve|'m|'ll|'d)?",
    r"[^\r\n\p{L}\p{N}]?[[\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}]&&[^\p{Han}]]+"
    r"[[\p{Ll}\p{Lm}\p{Lo}\p{M}]&&[^\p{Han}]]*(?i:'s|'t|'re|'ve|'m|'ll|'d)?",
    r"\p{N}{1,3}",
    r" ?[^\s\p{L}\p{N}]+[\r\n]*",
    r"\s*[\r\n]+",
    r"\s+(?!\S)",
    r"\s+",
])

CASES = [
    # --- the MVP gate and plain prose ---
    "The capital of France is",
    "the quick brown fox jumps over the lazy dog",
    "Hello, world!",
    # --- contractions: K3 attaches them, cl100k splits them ---
    "it's don't we're I've you'll he'd she's",
    "IT'S DON'T WE'RE",
    "It'S mIxEd'Ve case",
    "'s at the start",
    "trailing apostrophe' and ''double''",
    "o'clock rock'n'roll",
    # --- case transitions: the [U]*[L]+ backtracking ---
    "getHTTPResponse CamelCase XMLHttpRequest",
    "ABC abc AbC aBc",
    "NASA AND THE USA",
    "iOS macOS iPhone eBay",
    "AAAAbbbbCCCCdddd",
    "A",
    "a",
    "Ab",
    "aB",
    "ABc",
    "aBC",
    # --- Han and the Han/Latin boundary ---
    "中国的首都是北京",
    "Beijing 北京 is the capital",
    "北京Beijing",
    "Beijing北京",
    "漢字とひらがなとカタカナ",
    "한국어 텍스트",
    # --- numbers and punctuation ---
    "In 2026, GPT-4o cost $1,234.56!",
    "1234567890",
    "12 345 6789",
    "x=1+2*3;",
    "a...b---c___d",
    # --- whitespace and newlines ---
    "line one\nline two\r\nline three",
    "trailing spaces   ",
    "   leading spaces",
    "tabs\tand\tmore",
    "double\n\nnewline",
    "\n",
    "\n\n\n",
    " ",
    "   ",
    "a \n b",
    # --- non-Latin scripts (Lo, and marks) ---
    "Ελληνικά κείμενο",
    "Русский текст",
    "العربية نص",
    "עברית טקסט",
    "देवनागरी पाठ",
    "ไทย ข้อความ",
    # --- combining marks (category M is in BOTH letter classes) ---
    "é café",          # e + combining acute
    "ÀBĆ",
    "́leading mark",
    "नििमार्क",
    # --- emoji / symbols (neither L nor N) ---
    "hello 👋 world 🌍",
    "→ ← ↑ ↓",
    "100% sure — really",
    # --- alternation ORDER: found by scripts/fuzz_k3_pretok.py, not by hand ---
    # A combining mark (Mn) is BOTH a legal `[^\r\n\p{L}\p{N}]?` prefix and a legal
    # lower-ish run. When an uppercase letter follows, the reference falls back to a bare
    # alternative 2 (mark alone) rather than taking alternative 3 with the mark as prefix.
    # Getting the nesting backwards yields ["̧Б"] instead of ["̧", "Б"].
    "̧Б",
    "̈A",
    "́Z rest",
    "̧̈ABC",
    "β02̧Б:カE5̧Β",
    # A `Lo` is in both classes too, so `[U]*` must backtrack past it.
    "あA",
    "あAb",
    "カタA",
    "ʰX",
    "ǅあ",
    # --- adversarial / degenerate ---
    "",
    "'",
    "''",
    "'''",
    "a'",
    "'a",
    " nbsp",                  # non-breaking space is \s in Unicode
    "mixed 中文 and English and 123 and !!!",
    "Ünïcödé Mïxéd Câsé",
    "ß ẞ ﬁ ǅ ǆ Ǆ",                 # sharp s, ligature, titlecase digraph
]


def rust_str(s):
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    return '"%s"' % "".join(out)


def main():
    pat = regex.compile(K3_PAT, regex.V1)
    print("//! Kimi-K3 pre-tokenizer: differential test against the reference pattern.")
    print("//!")
    print("//! GENERATED by scripts/gen_k3_pretok_cases.py — do not edit by hand.")
    print("//!")
    print("//! Every expected split below was produced by running K3's ACTUAL `pat_str`")
    print("//! (from `tokenization_kimi.py`) through the `regex` module. They are not a")
    print("//! second reading of the pattern written out by hand, so this fails if the Rust")
    print("//! port misunderstands the pattern, not merely if it misimplements what I")
    print("//! believed the pattern to be.")
    print("//!")
    print("//! Regenerate after any change to the split, and diff the fixture.")
    print()
    print("use colibri_tokenizer::k3_pretokenize;")
    print()
    print("/// `(input, expected_pieces)` — see the module note on provenance.")
    print("#[rustfmt::skip]")
    print("const CASES: &[(&str, &[&str])] = &[")
    for s in CASES:
        pieces = [m.group() for m in pat.finditer(s)]
        assert "".join(pieces) == s, "pattern did not cover %r" % s
        print("    (%s, &[%s])," % (rust_str(s), ", ".join(rust_str(p) for p in pieces)))
    print("];")
    print()
    print("""#[test]
fn k3_pretokenize_matches_the_reference_pattern() {
    let mut bad = Vec::new();
    for (input, want) in CASES {
        let got = k3_pretokenize(input);
        if got != *want {
            bad.push(format!("input {input:?}\\n     got  {got:?}\\n     want {want:?}"));
        }
    }
    assert!(bad.is_empty(), "{} of {} cases differ:\\n{}", bad.len(), CASES.len(), bad.join("\\n"));
}

/// The pattern's alternatives cover every codepoint, so the pieces must reassemble the
/// input exactly — no character silently dropped by a gap between alternatives.
#[test]
fn k3_pretokenize_is_lossless() {
    for (input, _) in CASES {
        assert_eq!(k3_pretokenize(input).concat(), *input, "lost text on {input:?}");
    }
}""")
    print("\n// %d cases" % len(CASES), file=sys.stderr)


if __name__ == "__main__":
    main()
