#!/usr/bin/env python3
"""Emit the Unicode range tables Kimi-K3's pre-tokenizer needs, as Rust source.

colibrì's existing tables (`UNI_L`/`UNI_N`/`UNI_S`, from `scripts/gen_unicode.py`) cover
the cl100k pattern. K3's `pat_str` (in `tokenization_kimi.py`) needs three more classes
that the C header never carried:

  * `\\p{Han}`                                — its own leading alternative
  * `[\\p{Lu}\\p{Lt}\\p{Lm}\\p{Lo}\\p{M}] && [^\\p{Han}]`  ("upper-ish", non-Han)
  * `[\\p{Ll}\\p{Lm}\\p{Lo}\\p{M}] && [^\\p{Han}]`         ("lower-ish", non-Han)

Note the two letter classes OVERLAP: `Lm`, `Lo` and `M` are in both. They differ only in
that upper-ish carries `Lu`/`Lt` and lower-ish carries `Ll`. That is what makes K3 split
`getHTTPResponse` into `get` + `HTTPResponse` — a lower-ish run cannot absorb the
uppercase that follows it.

Usage:
    python3 scripts/gen_unicode_k3.py > crates/colibri-tokenizer/src/unicode_k3.rs

Needs the `regex` module for `\\p{Han}` (stdlib `unicodedata` exposes categories but not
scripts). Categories come from `unicodedata` so they track the running interpreter's
Unicode version, which is recorded in the generated header — the reference tokenizer
resolves the same pattern against `regex`'s own tables, so a version skew is the one
place this can drift from K3.
"""
import sys
import unicodedata

try:
    import regex
except ImportError:
    raise SystemExit("needs the `regex` module: pip install regex")

MAX_CP = 0x110000
han_re = regex.compile(r"\p{Han}")


def ranges(pred):
    """Collapse `pred` over the whole codepoint space into (lo, hi) inclusive ranges."""
    out = []
    start = None
    for cp in range(MAX_CP):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CP - 1))
    return out


def cat(cp):
    return unicodedata.category(chr(cp))


def is_han(cp):
    # Surrogates cannot be formed into a str for matching; they are not Han.
    if 0xD800 <= cp <= 0xDFFF:
        return False
    return bool(han_re.fullmatch(chr(cp)))


UPPER_CATS = {"Lu", "Lt", "Lm", "Lo", "Mn", "Mc", "Me"}
LOWER_CATS = {"Ll", "Lm", "Lo", "Mn", "Mc", "Me"}


def emit(name, pairs, doc):
    print("/// %s" % doc)
    print("#[rustfmt::skip]")
    print("pub static %s: &[(u32, u32)] = &[" % name)
    line = "    "
    for a, b in pairs:
        tok = "(0x%X, 0x%X)," % (a, b)
        if len(line) + len(tok) + 1 > 100:
            print(line.rstrip())
            line = "    "
        line += tok + " "
    if line.strip():
        print(line.rstrip())
    print("];")
    print()


def main():
    han = ranges(is_han)
    han_set = set()
    for a, b in han:
        han_set.update(range(a, b + 1))

    upper = ranges(lambda cp: cat(cp) in UPPER_CATS and cp not in han_set)
    lower = ranges(lambda cp: cat(cp) in LOWER_CATS and cp not in han_set)

    print("//! Unicode range tables for the **Kimi-K3** pre-tokenizer.")
    print("//!")
    print("//! GENERATED by scripts/gen_unicode_k3.py — do not edit by hand.")
    print("//! Unicode %s (from the generating interpreter's `unicodedata`)." % unicodedata.unidata_version)
    print("//!")
    print("//! See that script for what these classes are and why the two letter classes")
    print("//! overlap. `unicode_tables.rs` holds the cl100k tables; this file is additive.")
    print()
    print("use crate::unicode_tables::uni_in;")
    print()
    emit("K3_HAN", han, r"`\p{Han}` — K3 matches a Han run as its own leading alternative.")
    emit(
        "K3_UPPER",
        upper,
        r"`[\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}] && [^\p{Han}]` — the upper-ish letter class.",
    )
    emit(
        "K3_LOWER",
        lower,
        r"`[\p{Ll}\p{Lm}\p{Lo}\p{M}] && [^\p{Han}]` — the lower-ish letter class.",
    )
    print(r"/// `\p{Han}`.")
    print("#[inline] pub fn is_han(c: u32) -> bool { uni_in(K3_HAN, c) }")
    print(r"/// Upper-ish and non-Han: `Lu`, `Lt`, `Lm`, `Lo`, `M`.")
    print("#[inline] pub fn is_k3_upper(c: u32) -> bool { uni_in(K3_UPPER, c) }")
    print(r"/// Lower-ish and non-Han: `Ll`, `Lm`, `Lo`, `M`. Overlaps [`is_k3_upper`].")
    print("#[inline] pub fn is_k3_lower(c: u32) -> bool { uni_in(K3_LOWER, c) }")

    print(
        "\n// ranges: han=%d upper=%d lower=%d" % (len(han), len(upper), len(lower)),
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
