//! Kimi-K3 pre-tokenizer: differential test against the reference pattern.
//!
//! GENERATED by scripts/gen_k3_pretok_cases.py — do not edit by hand.
//!
//! Every expected split below was produced by running K3's ACTUAL `pat_str`
//! (from `tokenization_kimi.py`) through the `regex` module. They are not a
//! second reading of the pattern written out by hand, so this fails if the Rust
//! port misunderstands the pattern, not merely if it misimplements what I
//! believed the pattern to be.
//!
//! Regenerate after any change to the split, and diff the fixture.

use colibri_tokenizer::k3_pretokenize;

/// `(input, expected_pieces)` — see the module note on provenance.
#[rustfmt::skip]
const CASES: &[(&str, &[&str])] = &[
    ("The capital of France is", &["The", " capital", " of", " France", " is"]),
    ("the quick brown fox jumps over the lazy dog", &["the", " quick", " brown", " fox", " jumps", " over", " the", " lazy", " dog"]),
    ("Hello, world!", &["Hello", ",", " world", "!"]),
    ("it's don't we're I've you'll he'd she's", &["it's", " don't", " we're", " I've", " you'll", " he'd", " she's"]),
    ("IT'S DON'T WE'RE", &["IT'S", " DON'T", " WE'RE"]),
    ("It'S mIxEd'Ve case", &["It'S", " m", "Ix", "Ed'Ve", " case"]),
    ("'s at the start", &["'s", " at", " the", " start"]),
    ("trailing apostrophe' and ''double''", &["trailing", " apostrophe", "'", " and", " ''", "double", "''"]),
    ("o'clock rock'n'roll", &["o", "'clock", " rock", "'n", "'roll"]),
    ("getHTTPResponse CamelCase XMLHttpRequest", &["get", "HTTPResponse", " Camel", "Case", " XMLHttp", "Request"]),
    ("ABC abc AbC aBc", &["ABC", " abc", " Ab", "C", " a", "Bc"]),
    ("NASA AND THE USA", &["NASA", " AND", " THE", " USA"]),
    ("iOS macOS iPhone eBay", &["i", "OS", " mac", "OS", " i", "Phone", " e", "Bay"]),
    ("AAAAbbbbCCCCdddd", &["AAAAbbbb", "CCCCdddd"]),
    ("A", &["A"]),
    ("a", &["a"]),
    ("Ab", &["Ab"]),
    ("aB", &["a", "B"]),
    ("ABc", &["ABc"]),
    ("aBC", &["a", "BC"]),
    ("中国的首都是北京", &["中国的首都是北京"]),
    ("Beijing 北京 is the capital", &["Beijing", " ", "北京", " is", " the", " capital"]),
    ("北京Beijing", &["北京", "Beijing"]),
    ("Beijing北京", &["Beijing", "北京"]),
    ("漢字とひらがなとカタカナ", &["漢字", "とひらがなとカタカナ"]),
    ("한국어 텍스트", &["한국어", " 텍스트"]),
    ("In 2026, GPT-4o cost $1,234.56!", &["In", " ", "202", "6", ",", " GPT", "-", "4", "o", " cost", " $", "1", ",", "234", ".", "56", "!"]),
    ("1234567890", &["123", "456", "789", "0"]),
    ("12 345 6789", &["12", " ", "345", " ", "678", "9"]),
    ("x=1+2*3;", &["x", "=", "1", "+", "2", "*", "3", ";"]),
    ("a...b---c___d", &["a", "...", "b", "---", "c", "___", "d"]),
    ("line one\nline two\r\nline three", &["line", " one", "\n", "line", " two", "\r\n", "line", " three"]),
    ("trailing spaces   ", &["trailing", " spaces", "   "]),
    ("   leading spaces", &["  ", " leading", " spaces"]),
    ("tabs\tand\tmore", &["tabs", "\tand", "\tmore"]),
    ("double\n\nnewline", &["double", "\n\n", "newline"]),
    ("\n", &["\n"]),
    ("\n\n\n", &["\n\n\n"]),
    (" ", &[" "]),
    ("   ", &["   "]),
    ("a \n b", &["a", " \n", " b"]),
    ("Ελληνικά κείμενο", &["Ελληνικά", " κείμενο"]),
    ("Русский текст", &["Русский", " текст"]),
    ("العربية نص", &["العربية", " نص"]),
    ("עברית טקסט", &["עברית", " טקסט"]),
    ("देवनागरी पाठ", &["देवनागरी", " पाठ"]),
    ("ไทย ข้อความ", &["ไทย", " ข้อความ"]),
    ("é café", &["é", " café"]),
    ("ÀBĆ", &["ÀBĆ"]),
    ("́leading mark", &["́leading", " mark"]),
    ("नििमार्क", &["नििमार्क"]),
    ("hello 👋 world 🌍", &["hello", " 👋", " world", " 🌍"]),
    ("→ ← ↑ ↓", &["→", " ←", " ↑", " ↓"]),
    ("100% sure — really", &["100", "%", " sure", " —", " really"]),
    ("̧Б", &["̧", "Б"]),
    ("̈A", &["̈", "A"]),
    ("́Z rest", &["́", "Z", " rest"]),
    ("̧̈ABC", &["̧̈", "ABC"]),
    ("β02̧Б:カE5̧Β", &["β", "02", "̧", "Б", ":カ", "E", "5", "̧", "Β"]),
    ("あA", &["あ", "A"]),
    ("あAb", &["あAb"]),
    ("カタA", &["カタ", "A"]),
    ("ʰX", &["ʰ", "X"]),
    ("ǅあ", &["ǅあ"]),
    ("", &[]),
    ("'", &["'"]),
    ("''", &["''"]),
    ("'''", &["'''"]),
    ("a'", &["a", "'"]),
    ("'a", &["'a"]),
    (" nbsp", &[" nbsp"]),
    ("mixed 中文 and English and 123 and !!!", &["mixed", " ", "中文", " and", " English", " and", " ", "123", " and", " !!!"]),
    ("Ünïcödé Mïxéd Câsé", &["Ünïcödé", " Mïxéd", " Câsé"]),
    ("ß ẞ ﬁ ǅ ǆ Ǆ", &["ß", " ẞ", " ﬁ", " ǅ", " ǆ", " Ǆ"]),
];

#[test]
fn k3_pretokenize_matches_the_reference_pattern() {
    let mut bad = Vec::new();
    for (input, want) in CASES {
        let got = k3_pretokenize(input);
        if got != *want {
            bad.push(format!("input {input:?}\n     got  {got:?}\n     want {want:?}"));
        }
    }
    assert!(bad.is_empty(), "{} of {} cases differ:\n{}", bad.len(), CASES.len(), bad.join("\n"));
}

/// The pattern's alternatives cover every codepoint, so the pieces must reassemble the
/// input exactly — no character silently dropped by a gap between alternatives.
#[test]
fn k3_pretokenize_is_lossless() {
    for (input, _) in CASES {
        assert_eq!(k3_pretokenize(input).concat(), *input, "lost text on {input:?}");
    }
}

// --- pre-tokenizer selection -----------------------------------------------------
// Hand-written (not generated): these assert which split a tokenizer.json selects, which
// is about detection rather than the pattern itself.

use colibri_json::Json;
use colibri_tokenizer::{PreTok, Tokenizer};

/// A minimal but valid tokenizer.json carrying `pre_tokenizer_json` verbatim.
fn tok_with_pretok(pre: &str) -> Tokenizer {
    let src = format!(
        r#"{{"pre_tokenizer":{pre},
             "model":{{"type":"BPE","vocab":{{"a":0,"b":1}},"merges":[]}}}}"#
    );
    Tokenizer::from_json(&Json::parse(&src).unwrap()).unwrap()
}

/// K3's pattern selects the K3 split.
#[test]
fn k3_pattern_selects_the_k3_split() {
    let pre = r#"{"type":"Sequence","pretokenizers":[
        {"type":"Split","pattern":{"Regex":"[\\p{Han}]+|[^\\r\\n\\p{L}\\p{N}]?[[\\p{Lu}\\p{Lt}\\p{Lm}\\p{Lo}\\p{M}]&&[^\\p{Han}]]*[[\\p{Ll}\\p{Lm}\\p{Lo}\\p{M}]&&[^\\p{Han}]]+"},
         "behavior":"Isolated","invert":false}]}"#;
    assert_eq!(tok_with_pretok(pre).pretok(), PreTok::KimiK3);
}

/// The cl100k pattern — and an absent `pre_tokenizer` — stay on the cl100k split.
#[test]
fn cl100k_and_missing_pretokenizer_stay_cl100k() {
    let cl = r#"{"type":"Split","pattern":{"Regex":"(?i:'s|'t)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}{1,3}"},
                 "behavior":"Isolated","invert":false}"#;
    assert_eq!(tok_with_pretok(cl).pretok(), PreTok::Cl100k);
    assert_eq!(tok_with_pretok("null").pretok(), PreTok::Cl100k);
}

/// Naming Han is NOT enough to select K3 — a Qwen-style split does that and must keep
/// cl100k. Only the `&&` class intersection, which is K3-specific, flips it.
#[test]
fn a_han_naming_pattern_alone_does_not_select_k3() {
    let qwen_ish = r#"{"type":"Split","pattern":{"Regex":"[\\p{Han}]+|\\p{L}+|\\p{N}"},
                       "behavior":"Isolated","invert":false}"#;
    assert_eq!(tok_with_pretok(qwen_ish).pretok(), PreTok::Cl100k);
}
